"""Regenerate the code-derived documentation so it never drifts from the implementation:
docs/RBAC_MATRIX.md, docs/API.md and docs/DATA_DICTIONARY_TABLES.md.   Usage:  python start_scripts/gen_docs.py
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "backend"), str(ROOT)]
os.environ.setdefault("DATABASE_URL", f"sqlite:///{tempfile.mkdtemp()}/doc.db")
os.environ.setdefault("SIM_ENABLED", "false")

from app.db import Base  # noqa: E402
from app import models  # noqa: E402,F401
from app.main import create_app  # noqa: E402
from app.rbac import INTEL_ELIGIBLE_ROLES, P, ROLE_INFO, ROLE_PERMISSIONS  # noqa: E402

DOCS = ROOT / "docs"
HDR = "<!-- GENERATED by start_scripts/gen_docs.py — do not edit by hand -->\n\n"


def rbac():
    roles = list(ROLE_PERMISSIONS)
    out = [HDR, "# Role-Based Access Control Matrix\n\n",
           "Authorisation = **identity + rank + role + posting + jurisdiction + need-to-know**. The matrix shows what each role "
           "*may* do; jurisdiction (STATE / DISTRICT / STATION / UNIT) then limits *which records* it applies to, and the "
           "intelligence permissions additionally require the per-user need-to-know flag (`User.intel_access`) on an intel-eligible role.\n\n",
           "## Roles\n\n| Role | Title | Default jurisdiction | Login landing | Intel-eligible |\n|---|---|---|---|---|\n"]
    for r in roles:
        i = ROLE_INFO[r]
        out.append(f"| `{r}` | {i.label} | {i.default_jurisdiction} | {i.landing_label} (`{i.landing}`) | {'yes' if r in INTEL_ELIGIBLE_ROLES else '**no**'} |\n")
    out.append("\n## Permission matrix\n\n● granted · ◐ granted only with need-to-know flag · blank = not granted\n\n")
    out.append("| Permission | Meaning | " + " | ".join(roles) + " |\n|---|---|" + "---|" * len(roles) + "\n")
    for p, desc in P.items():
        cells = []
        for r in roles:
            has = p in ROLE_PERMISSIONS[r]
            cells.append(("◐" if p.startswith("INTEL") and r in INTEL_ELIGIBLE_ROLES else "●") if has and (not p.startswith("INTEL") or r in INTEL_ELIGIBLE_ROLES) else "")
        out.append(f"| `{p}` | {desc} | " + " | ".join(cells) + " |\n")
    out.append("\n## Separation rules enforced in code\n\n"
               "* `SYSTEM_ADMIN` and `CYBER_ADMIN` are never intel-eligible; the Users API rejects granting them `intel_access`.\n"
               "* Asset tasking (`TASK_ASSETS`) is restricted to supervisory ranks/roles; ICCC operators verify but cannot task.\n"
               "* Field order transitions require `ORDERS_FIELD` **and** being a recipient (assigned asset, crew member, station IIC).\n"
               "* IIC / SP / DSP jurisdiction limits tasking, personnel and asset edits to their own station / district.\n"
               "* Incident closure (C7) requires `INCIDENT_CLOSE`; verification (C2) requires `INCIDENT_VERIFY`.\n"
               "* Every denied request is written to the audit log with outcome `DENIED`.\n"
               "* Role / access changes revoke the affected user's active sessions.\n")
    (DOCS / "RBAC_MATRIX.md").write_text("".join(out))


def api():
    spec = create_app().openapi()
    out = [HDR, "# API Reference\n\n", "Interactive OpenAPI UI: `http://localhost:8000/docs` · schema: `/openapi.json`.\n\n",
           "All `/api/*` endpoints except `/api/public/*` and `/api/auth/login` require `Authorization: Bearer <token>` "
           "(obtained from `POST /api/auth/login`). Authorisation is enforced server-side per endpoint (see RBAC_MATRIX.md).\n\n"]
    groups: dict[str, list] = {}
    for path, ops in sorted(spec["paths"].items()):
        for method, op in ops.items():
            tag = (op.get("tags") or ["other"])[0]
            groups.setdefault(tag, []).append((method.upper(), path, op.get("summary", "")))
    for tag, rows in groups.items():
        out.append(f"## {tag}\n\n| Method | Path | Summary |\n|---|---|---|\n")
        for m, p, s in rows:
            out.append(f"| {m} | `{p}` | {s} |\n")
        out.append("\n")
    (DOCS / "API.md").write_text("".join(out))


def data_dictionary():
    out = [HDR, "# Data Dictionary — tables and columns\n\n",
           "Generated from the SQLAlchemy model (`backend/app/models.py`). Semantics are explained in DATA_DICTIONARY.md.\n\n"]
    for t in Base.metadata.sorted_tables:
        out.append(f"## `{t.name}`\n\n| Column | Type | Null | Key |\n|---|---|---|---|\n")
        for c in t.columns:
            key = "PK" if c.primary_key else (f"FK → {list(c.foreign_keys)[0].target_fullname}" if c.foreign_keys else ("unique" if c.unique else ""))
            out.append(f"| `{c.name}` | {c.type} | {'yes' if c.nullable else 'no'} | {key} |\n")
        out.append("\n")
    (DOCS / "DATA_DICTIONARY_TABLES.md").write_text("".join(out))


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    rbac()
    api()
    data_dictionary()
    print("Generated RBAC_MATRIX.md, API.md, DATA_DICTIONARY_TABLES.md")
